#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app_register:
#   path: /inscription
#   controller: App\Controller\RegistrationController::app_register
#   methods: [GET, POST]
